name: Destroy AWS 3-Tier Infrastructure

on:
  workflow_dispatch:  # Allows you to trigger it manually from the GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.3.5"  # Use the desired Terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-south-1"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan (Destroy)
      run: terraform plan -destroy -out=tfplan

    - name: Terraform Destroy
      run: terraform apply -auto-approve tfplan
